version: 1
formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  file_handler:
    class: logging.FileHandler
    formatter: simple
    filename: logs/placeholder.log  # Will be overwritten dynamically in app.py

root:
  level: INFO
  handlers: [file_handler]
